---
  - name: "install required package"
    pip:
      name: "{{ packages }}"

  - name: "install awscli package"
    yum:
      name: "awscli"
      state: present
      update_cache: yes

  - name: Create .aws directory
    file:
      path: ~/.aws
      state: directory
      owner: prod_ansible
      group: prod_ansible

  - name: "Copy config "
    template:
      src: config.j2
      dest: ~/.aws/config
      owner: prod_ansible
      group: prod_ansible
      mode: '0600'

  - name: "Copy credentials"
    copy:
      src: credentials
      dest: ~/.aws/credentials
      owner: prod_ansible
      group: prod_ansible
      mode: '0600'
