---
  - name: "download awscli package"
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp
      remote_src: yes

  - name: "Install awscli"
    shell: /tmp/aws/install --update


  - name: "install required package"
    pip:
      name: "{{ packages }}"


  - name: Create .aws directory
    file:
      path: /home/prod_ansible/.aws
      state: directory
      owner: prod_ansible
      group: prod_ansible

  - name: "Copy config "
    template:
      src: config.j2
      dest: /home/prod_ansible/.aws/config
      owner: prod_ansible
      group: prod_ansible
      mode: '0600'

  - name: "Copy credentials"
    copy:
      src: credentials
      dest: /home/prod_ansible/.aws/credentials
      owner: prod_ansible
      group: prod_ansible
      mode: '0600'
