---
  - name: "download awscli package"
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp
      remote_src: yes

  - name: "Install awscli"
    shell: /tmp/aws/install --update


  - name: "install required package"
    pip:
      name: "{{ packages }}"


  - name: Create .aws directory
    file:
      path: ~/.aws
      state: directory
      owner: mkazmi
      group: staff

  - name: "Copy config "
    template:
      src: config.j2
      dest: ~/.aws/config
      owner: mkazmi
      group: staff
      mode: '0600'

  - name: "Copy credentials"
    copy:
      src: credentials
      dest: ~/.aws/credentials
      owner: mkazmi
      group: staff
      mode: '0600'
