---
  - name: create Private Routing Tables
    ec2_vpc_route_table:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ region_id }}"
      vpc_id: "{{ vpc_id }}"
      tags:
        Name: "{{ PrivRT }}"
      state: present
      subnets:
        - "{{ PrivSub_1A }}"
        - "{{ PrivSub_1B }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw_id }}"
      nat_gateway_id: "{{ Nat_gw_id }}"
    register: result
  - name: "Set Private Routing Table id in Variable"
    set_fact:
      privrt_id: "{{ result.route_table.id }}"
  - debug:
      msg:
        - "{{ privrt_id }}"
