---
  - name: "Create Public Routing Tables"
    ec2_vpc_route_table:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ region_id }}"
      vpc_id: "{{ vpc_id }}"
      tags:
        Name: "{{ PubRT }}"
      state: present
      subnets:
        - "{{ PubSub_1AA }}"
        - "{{ PubSub_1B }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw_id }}"
    register: result
  - name: "Set Public Routing Table id in Variable"
    set_fact:
      pubrt_id: "{{ result.route_table.id }}"
  - debug:
      msg:
      - "{{ pubrt_id }}"
