---
  - name: Setup AWS CLI (1/3)
    shell: >
      aws configure set aws_access_key_id "{{ aws_access_key }}"

  - name: Setup AWS CLI (2/3)
    shell: >
      aws configure set aws_secret_access_key "{{ aws_secret_key }}"

  - name: Setup AWS CLI (3/3)
    shell: >
      aws configure set region {{ region_id }}

  - name: Create Elastic IP
    shell: >
      aws ec2 allocate-address --domain vpc --query AllocationId | tr -d '"'
    register: eip

  - debug: var=eip

  - name: Set EIP in variable
    set_fact:
      my_elastic_ip: "{{ eip.stdout }}"
