---
  - name: Setup AWS CLI (1/3)
    shell: >
      aws configure set aws_access_key_id "{{ aws_access_key_id }}"

  - name: Setup AWS CLI (2/3)
    shell: >
      aws configure set aws_secret_access_key "{{ aws_secret_access_key }}"

  - name: Setup AWS CLI (3/3)
    shell: >
      aws configure set region {{ region_id }}

  - name: Create Elastic IP
    shell: >
      aws ec2 allocate-address --domain vpc --query AllocationId | tr -d '"'
    register: result

  - name: "Set Elastic IP in Variable"
    set_fact:
      my_elastic_ip: "{{ result.stdout_lines }}"
  - debug:
      msg:
      - "{{ my_elastic_ip }}"
