---
  - name: create Internet Gateway
    ec2_vpc_igw:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ region_id }}"
      vpc_id: "{{ vpc_id }}"
      tags:
        Name: "{{ IGW }}"
      state: present
    register: result
  - name: "Set Internet-GW id in Variable"
    set_fact:
      igw_id: "{{ result.gateway_id }}"
  - debug:
      msg:
      - "{{ igw_id }}"
#
