---
  - name: create a VPC with default tenancy and a couple of tags
    ec2_vpc_net:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      name: "{{ VpcName }}"
      cidr_block: "{{ CidrBlock }}"
      region: "{{ RegionName }}"
      dns_hostnames: yes
      tenancy: default
      dns_hostnames: yes
      dns_support: yes
      state: present
    register: result
  - name: "Settings region in Variable"
    set_fact:
      region_id: "{{ RegionName }}"
  - debug:
      msg:
      - "{{ region_id }}"

  - name: "Set VPC id in Variable"
    set_fact:
      vpc_id: "{{ result.vpc.id }}"
  - debug:
      msg:
      - "{{ vpc_id }}"

  - name: "Set IGW Name in Variable"
    set_fact:
      IGW: "{{ IGWName }}"
  - debug:
      msg: "{{ IGW }}"
#public RT
  - name: "Set Public Routing Table Name in Variable"
    set_fact:
      PubRT: "{{ PubRtable_a_01 }}"
  - debug:
      msg: "{{ PubRT }}"
#Private RT
  - name: "Set Private Routing Table Name in Variable"
    set_fact:
      PrivRT: "{{ PrivRtable_b_01 }}"
  - debug:
      msg: "{{ PrivRT }}"
#Pubsub AZ-1
  - name: "Set Public AZ-1 Name in Variable"
    set_fact:
      AZ_1: "{{ ca_central_1A }}"
  - debug:
      msg: "{{ AZ_1 }}"

  - name: "Set Public Subnet Name in Variable"
    set_fact:
      PubSub1a: "{{ PubSubnet_a_1 }}"
  - debug:
      msg: "{{ PubSub1a }}"

  - name: "Set Public CIDR in Variable"
    set_fact:
      PubCidr_1a: "{{ PubCIDR_a_1 }}"
  - debug:
      msg: "{{ PubCidr_1a }}"
#Privsub AZ-1
  - name: "Set Private Subnet Name in Variable"
    set_fact:
      PriSub_1a: "{{ PriSubnet_a_1 }}"
  - debug:
      msg: "{{ PriSub_1a }}"

  - name: "Set Private CIDR in Variable"
    set_fact:
      PriCidr_1a: "{{ PriCIDR_a_1 }}"
  - debug:
      msg: "{{ PriCidr_1a }}"

##AZ-2
#Pubsub AZ-2
  - name: "Set Public AZ-1 Name in Variable"
    set_fact:
      AZ_2: "{{ ca_central_1B }}"
  - debug:
      msg: "{{ AZ_2 }}"

  - name: "Set AZ-2 Public Subnet Name in Variable"
    set_fact:
      PubSub1b: "{{ PubSubnet_b_1 }}"
  - debug:
      msg: "{{ PubSub1b }}"

  - name: "Set AZ-2 Public CIDR in Variable"
    set_fact:
      PubCidr_1b: "{{ PubCIDR_b_1 }}"
  - debug:
      msg: "{{ PubCidr_1b }}"
#Privsub AZ-2
  - name: "Set AZ-2 Private Subnet Name in Variable"
    set_fact:
      PriSub_1b: "{{ PriSubnet_b_1 }}"
  - debug:
      msg: "{{ PriSub_1b }}"

  - name: "Set AZ-2 Private CIDR in Variable"
    set_fact:
      PriCidr_1b: "{{ PriCIDR_b_1 }}"
  - debug:
      msg: "{{ PriCidr_1b }}"
  - name: "Set Bastion Hsot AMI ID in Variable"
    set_fact:
      BhostAmi: "{{ Bhost }}"
  - name: "Set Bastion Hsot Name in Variable"
    set_fact:
      BhostName: "{{ BhostN }}"
